clang-tidy: fix invalid enum scoping in occ_status
Enums for ThrottleReasons were incorrectly referenced through the
object instance (e.g., throttleHandle->ThrottleReasons::PowerLimit),
which is invalid C++ and fails under clang-tidy due to stricter name
lookup rules.

Fixed below error
'''
../occ_status.cpp:622:54: error: 'sdbusplus::common::xyz::openbmc_project::control::power::Throttle::ThrottleReasons::PowerLimit' is not a member of class 'sdbusplus::server::object::object<sdbusplus::server::xyz::openbmc_project::control::power::Throttle>'
  622 |                     throttleHandle->ThrottleReasons::PowerLimit);
      |                                     ~~~~~~~~~~~~~~~~~^
../occ_status.cpp:627:54: error: 'sdbusplus::common::xyz::openbmc_project::control::power::Throttle::ThrottleReasons::ThermalLimit' is not a member of class 'sdbusplus::server::object::object<sdbusplus::server::xyz::openbmc_project::control::power::Throttle>'
  627 |                     throttleHandle->ThrottleReasons::ThermalLimit);
      |                                     ~~~~~~~~~~~~~~~~~^
../occ_status.cpp:632:54: error: 'sdbusplus::common::xyz::openbmc_project::control::power::Throttle::ThrottleReasons::ManagementDetectedFault' is not a member of class 'sdbusplus::server::object::object<sdbusplus::server::xyz::openbmc_project::control::power::Throttle>'
  632 |                     throttleHandle->ThrottleReasons::ManagementDetectedFault);
      |                                     ~~~~~~~~~~~~~~~~~^
'''

Change-Id: Ibceb682d28148b3a686b07c1cb2b13faf316dfad
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>