clang-tidy: initialize event and pointers to nullptr
Clang-tidy warned about uninitialized fields being used in the
constructor initializer list.

Fixed below errors
'''
../test/error_files_tests.cpp:27:46: error: field 'event' is uninitialized when used here [-Werror,-Wuninitialized]
../test/utest.cpp:18:46: error: field 'event' is uninitialized when used here [-Werror,-Wuninitialized]
'''

Change-Id: Ie60d7a3fbe5a3ce2f7a9a2ffe898c18584616f9f
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>