clang-tidy: remove unused private field
Drop unused private member 'manager' from powermode.hpp to resolve
-Wunused-private-field warning. No functional change.

Fixed below error
'''
../powermode.hpp:352:20: error: private field 'manager' is not used [-Werror,-Wunused-private-field]
  352 |     const Manager& manager;
'''

Change-Id: I0ddf0414b8193637fced2679280e53fa4cc1aa1f
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>