clang-tidy: add explicit optional guards
Add has_value() checks before dereferencing pldmInstanceID in
prepareSetEffecterReq and encodeGetStateSensorRequest to satisfy
clang-tidy bugprone-unchecked-optional-access. Also extract a
local const instanceId in sendPldm for logging instead of using
pldmInstanceID.value() directly. These changes avoid warnings
without altering functional behavior.

Fixed below errors
'''
../pldm.cpp:424:9: error: unchecked access to optional value [bugprone-unchecked-optional-access,-warnings-as-errors]
  424 |         pldmInstanceID.value(), effecterId, effecterCount, stateField.data(),
../pldm.cpp:716:47: error: unchecked access to optional value [bugprone-unchecked-optional-access,-warnings-as-errors]
  716 |                       "INST", instance, "ID", pldmInstanceID.value(), "LEN",
../pldm.cpp:1117:55: error: unchecked access to optional value [bugprone-unchecked-optional-access,-warnings-as-errors]
 1117 |     auto msgRc = encode_get_state_sensor_readings_req(pldmInstanceID.value(),
'''

Change-Id: I5dcbaa7760b4de26368ef51edad8295b3c7341ad
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>