clang-tidy: add missing override
Mark setMode  with override to match the base and silence
-Winconsistent-missing-override. No functional change.

Fixed below error
'''
../occ_pass_through.hpp:65:10: error: 'setMode' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
   65 |     bool setMode(const uint8_t mode, const uint16_t modeData);
'''

Change-Id: I9daa8b34a146d05e1b8d89e2c980b279af443acc
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>