clang-tidy: delete default constructor
Default constructor was invalid for class semantics and caused
clang-tidy/Clang diagnostics. Mark the default constructor as
`=delete` to prevent accidental default construction and keep
-Werror builds green. No functional changes.

Fixed below errors (example)
'''
../occ_errors.hpp:36:12: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
   36 |     Error& operator=(Error&&) = default;
'''

Change-Id: I08d6a6e84bb98fe5e5c01265f494e2eb5eaf6bf0
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>